### ISSUE TITLE
Console stacktrace- Could not pass FMLServerStartedEvent to Plugin{id=prism

### ISSUE THREAD

**Issue by ProsperCraft** [LXGaming/PrismPlus#1]
https://gist.github.com/ProsperCraft/668657546799527e6adf68f33081fa57

Anything you can do here? or just ignore it?

**Comment by LXGaming** [comment]
Are you using MongoDB for your storage?

`org/bson/conversions/Bson` is only referenced in `MongoStorageAdapter` and `MongoRecords` classes

You need to make sure you get this build [Prism-3.0.0-beta2-46-ge820b5e-all.jar](http://helion3.com:8080/job/Prism/lastSuccessfulBuild/artifact/build/libs/Prism-3.0.0-beta2-46-ge820b5e-all.jar) as stated here [https://github.com/prism/Prism#downloads](https://github.com/prism/Prism#downloads)

**Comment by ProsperCraft** [comment]
Yes, Mongo It was recommended by the prism author.

I got all now, testing.

**Comment by ProsperCraft** [comment]
Fixed with -all
