### ISSUE TITLE
Console stacktrace - Could not pass ChangeBlockEvent$Place$Impl to Plugin

### ISSUE THREAD

**Issue by ProsperCraft** [LXGaming/PrismPlus#3]
https://gist.github.com/ProsperCraft/cb257c99b911f6c4ceba59d8195c7c55

**Comment by LXGaming** [comment]
This is an issue with Prism or Sponge, It appears to be happening when a block is placed. Do you know if every block is doing this or is it a specific one?

**Comment by ukdyl94** [comment]
Seems to be every block by the way it spams console.

**Comment by LXGaming** [comment]
Can you test using this build: https://github.com/prism/Prism/releases/tag/3.0.0-beta2-75-g9b005fd
It will print the block location into console which can use to track down the specific block causing this issue.

Make sure you remove PrismPlus as it won't be compatible with this version of Prism

**Comment by LXGaming** [comment]
This repository is being archived. If this is still an issue then please open it on [Prism](https://github.com/Prism/Prism)
